stages:
  convert_to_csv:
    cmd: python src/convert_to_csv.py
    deps:
      - src/convert_to_csv.py
      - ${all.paths.data.raw.health_centers}
      - ${all.paths.data.raw.dengue}
      - ${all.paths.data.raw.ovitraps}
    outs:
      - ${all.paths.data.raw.health_centers_csv}:
          persist: true
      - ${all.paths.data.raw.dengue_csv}:
          persist: true
      - ${all.paths.data.raw.ovitraps_csv}:
          persist: true
  raw_data_test:
    cmd: 
      - pytest test/data/raw/test_raw_data.py
      - pytest test/data/raw/test_raw_data_comparison.py
    deps:
      - test/data/raw/test_raw_data.py
      - test/data/raw/test_raw_data_comparison.py
      - ${all.paths.data.raw.ovitraps_csv}
      - ${all.paths.data.raw.dengue_csv}
      - ${all.paths.data.raw.health_centers_csv}
    outs:
      - ${all.paths.test.data.raw.diagnosis_raw_comparison}:
          persist: true
      - ${all.paths.test.data.raw.diagnosis_raw_data}:
          persist: true

  slow_processing:
    cmd: python src/process_data_slow.py
    deps:
      - src/process_data_slow.py
      - ${all.paths.data.raw.health_centers_csv}
      - ${all.paths.data.raw.dengue_csv}
      - ${all.paths.data.raw.ovitraps_csv}
    outs:
      - ${all.paths.data.processed.slow.health_centers}:
          persist: true
      - ${all.paths.data.processed.slow.dengue}:
          persist: true
      - ${all.paths.data.processed.slow.ovitraps}:
          persist: true

  fast_processing:
    cmd: python src/process_data_fast.py
    deps:
      - src/process_data_fast.py
      - ${all.paths.data.processed.slow.health_centers}
      - ${all.paths.data.processed.slow.dengue}
      - ${all.paths.data.processed.slow.ovitraps}
    outs:
      - ${all.paths.data.processed.health_centers}
      - ${all.paths.data.processed.dengue}
      - ${all.paths.data.processed.ovitraps}
      
  daily_ovitraps:
    cmd: python src/daily_ovitraps.py
    deps:
      - src/daily_ovitraps.py
      - ${all.paths.data.processed.ovitraps}
    outs:
      - ${all.paths.data.processed.daily_ovitraps}

  process_data_test:
    cmd: pytest test/data/processed/test_processed_data.py
    deps:
      - test/data/processed/test_processed_data.py
      - ${all.paths.data.processed.health_centers}
      - ${all.paths.data.processed.dengue}
      - ${all.paths.data.processed.ovitraps}
      - ${all.paths.data.processed.daily_ovitraps}

  libraries_tests:
    cmd: pytest test/utils/test_project_utils.py
    deps:
      - test/utils/test_project_utils.py
      - utils/project_utils.py
      - utils/generic.py