all:
  paths:
    data:
      raw:
        folder: data/raw/
        ovitraps: data/raw/MasterDataExtend062025_v2.xlsx
        dengue: data/raw/Dengue2007_2025.xlsx
        health_centers: data/raw/CENTRO_SAUDE_new.xlsx
        ibge_2010_population: data/raw/IBGE/2010/population/Base_informacoes_setores2010_sinopse_MG.xls
        ibge_2022_population: data/raw/IBGE/2022/population/Agregados_por_setores_basico_BR_20250417.csv
        ibge_sector_history: data/raw/IBGE/Historico_formacao_Setores_Censitarios_2010_2022.xlsx
      dvc:
        convert_to_csv:
          folder: data/dvc/convert_to_csv/
          health_centers_csv: data/dvc/convert_to_csv/health_centers.csv
          dengue_csv: data/dvc/convert_to_csv/dengue.csv
          ovitraps_csv: data/dvc/convert_to_csv/ovitraps.csv
          ibge_2010_population_csv: data/dvc/convert_to_csv/ibge_2010_population.csv
          ibge_2022_population_csv: data/dvc/convert_to_csv/ibge_2022_population.csv
          ibge_sector_history_csv: data/dvc/convert_to_csv/ibge_sector_history.csv
        process_population_data:
          folder: data/dvc/process_population_data/
          population_2010_to_2022: data/dvc/process_population_data/population_data.csv
          sectors_geojson: data/dvc/process_population_data/bh_sectors_2022_with_populations.geojson
          population_interpolated: data/dvc/process_population_data/interpolated_population_data.csv
        process_data:
          folder: data/dvc/process_data/
          health_centers: data/dvc/process_data/health_centers.csv
          dengue: data/dvc/process_data/dengue_data.csv
          ovitraps: data/dvc/process_data/ovitraps_data.csv
          daily_ovitraps: data/dvc/process_data/daily_ovitraps_data.csv
        add_population_info:
          folder: data/dvc/add_population_info/
          ovitraps: data/dvc/add_population_info/ovitraps_data.csv
          dengue: data/dvc/add_population_info/dengue_data.csv
          dengue_per_capita: data/dvc/add_population_info/dengue_per_capita.csv
          centroids: data/dvc/add_population_info/bh_sectors_2022_centroids.csv
          centroids_idw: data/dvc/add_population_info/sector_centroids_with_idw.csv
          dengue_citywide_per_capita: data/dvc/add_population_info/dengue_citywide_per_capita.csv
    test:
      data:
        raw:
          folder: test/data/raw/
          diagnosis_raw_data: test/data/raw/diagnosis_raw_data.txt
          diagnosis_raw_comparison: test/data/raw/diagnosis_raw_comparison.txt

skater:
  mst_cost: egg_corr_dist
  prune_obj: eggs_dengue_corr
  k_min: 2
  k_max: 6
  C_max: 30
  N_min: 20
  S_min: 3
  mst_min_overlap: 10
  epidemic_years:
    - "2012_13"
    - "2015_16"
    - "2018_19"
    - "2023_24"
  seed: 42
