all:
  paths:
    data:
      raw:
        folder: data/raw/
        ovitraps: data/raw/MasterDataExtend062025_v2.xlsx
        dengue: data/raw/Dengue2007_2025.xlsx
        health_centers: data/raw/CENTRO_SAUDE_new.xlsx
        ovitraps_csv: data/raw/MasterDataExtend062025_v2.csv
        dengue_csv: data/raw/Dengue2007_2025.csv
        health_centers_csv: data/raw/CENTRO_SAUDE_new.csv
      processed: 
        folder: data/processed/
        ovitraps: data/processed/ovitraps_data.csv
        dengue: data/processed/dengue_data.csv
        health_centers: data/processed/health_centers.csv
        daily_ovitraps: data/processed/daily_ovitraps_data.csv
        slow:
          folder: data/processed/slow/
          ovitraps: data/processed/slow/ovitraps_data.csv
          dengue: data/processed/slow/dengue_data.csv
          health_centers: data/processed/slow/health_centers.csv
    test:
      data:
        raw:
          folder: test/data/raw/
          diagnosis_raw_data: test/data/raw/diagnosis_raw_data.txt
          diagnosis_raw_comparison: test/data/raw/diagnosis_raw_comparison.txt